### ISSUE TITLE
Will this work with Nano?

### ISSUE THREAD

**Issue by brtknr** [GrgoMariani/NVidia-Jetson-DHT22-Python#2]

**Comment by grimar2008** [comment]
It should be able to work with it. However those pin defines should be added as well.
You should then define the pin number in the C_DHT.c file.
https://www.jetsonhacks.com/nvidia-jetson-nano-j41-header-pinout/
PIN0 is for dht #1 and PIN1 for #2
Be aware that this is not kernel based so the timings might be off which is why some readings could be misread.
